# =================== Application ===================
spring.application.name=LinkSnap
server.port=8081

# =================== Database ===================
spring.datasource.url=jdbc:postgresql://localhost:5433/linksnap
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA + Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =================== Redis ===================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =================== Custom App Properties ===================
app.short-code.length=8
app.rate-limit.requests=10
app.rate-limit.window-minutes=1
app.cache.redirect-ttl=3600   

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Connection settings
spring.datasource.hikari.connection-timeout=30000